### ISSUE TITLE
React web pack build error in phosphor icons

### ISSUE THREAD

**Issue by nitish-javis** [phosphor-icons/react#99]
![WhatsApp Image 2024-06-11 at 3 31 58 PM](https://github.com/phosphor-icons/react/assets/106834328/9574c7ec-7df3-40c1-924d-5646b97d3d94)

I'm facing this bug while doing `npm run build`. Tried to debug but couldn't find anything useful. But when I removed the phosphor icon library, then build worked fine.

OS: Mac
Browser: Chrome

If anyone could help me here, it would be a great help.
Thanks

**Comment by rektdeckard** [comment]
This is a pretty classic out-of-memory error that unfortunately happens because your build process is probably trying to load thousands of icons into memory while bundling, which is usually not necessary.

You can fix this a few ways:

1. Use full import paths for each icon, so that the bundler only loads what you use:
```ts
// this
import { Check } from "@phosphor-icons/react/dist/csr/Check";
import { Smiley } from "@phosphor-icons/react/dist/csr/Smiley";
// instead of this
import { Check, Smiley } from "@phosphor-icons/react";
```
2. Increase the memory limit of the Node process. By default, I believe, Node only allocates 1024MB per process, and this error occurs when it tries to allocate something new and doesn't find enough memory remaining. You can give it more memory  by changing the `max-old-space-size` option by setting an environment variable before calling your command:
```sh
export NODE_OPTIONS="--max-old-space-size=4096"
npm run build
```
You can also just add it to the script in `package.json`:
```json
{
  "scripts": {
    "build": "NODE_OPTIONS='--max-old-space-size=4096' vite build"
  }
}
```

Obviously the rest of your build command will differ based on the tools you're using, but it should work with everything. You can play around with the number, but 4GB should be plenty.

**Comment by ChiragDugar02** [comment]
Hi @rektdeckard , 

We changed the imports according to your suggestion and we also tried running the server by increasing the node memory allocated. It still doesn't work. However, this time it throws some other error. 


![Uploading Screenshot 2024-06-12 at 12.52.06 PM.png…]()

**Comment by ChiragDugar02** [comment]
Hi @rektdeckard ,

We changed the imports according to your suggestion and we also tried running the server by increasing the node memory allocated. It still doesn't work. However, this time it throws some other error.

<img width="1400" alt="Screenshot 2024-06-12 at 12 52 06 PM" src="https://github.com/phosphor-icons/react/assets/70942776/63f05ede-1dd9-40b3-b8d1-c83d72aacc55">

**Comment by rektdeckard** [comment]
That error is entirely different, and looks to be webpack [exceeding the maximum string length](https://github.com/webpack/webpack/issues/4629) in Node, which depending on your version of Node could be as low as ~260MB. I am not here to debug your application, but it sounds like you have some problems in your build setup.

Try upgrading Node (and webpack) if you're on an old version, look for anything that is concatenating into a massive string, and maybe try doing some debugging yourself.

**Comment by rektdeckard** [comment]
BTW it looks like you are using Node 15, which reached End Of Life like 2 years ago. Upgrading may resolve the problem, as memory allocation has undoubtedly improved in 9 major versions of Node.

**Comment by rektdeckard** [comment]
Closing as out-of-scope. This is simply too old a runtime for us to support.
